### ISSUE TITLE
Rewards doesn't work properly 

### ISSUE THREAD

**Issue by SpicyForthProgrammer** [CorvetteCole/NOHS-Edge-Client#2]

**Comment by SpicyForthProgrammer** [comment]
Also most sub pages revert back to the main menu

**Comment by SpicyForthProgrammer** [comment]
Excluding edge

**Comment by CorvetteCole** [comment]
yeah if you click on them again after they've returned you to the main page then it won't happen again. has something to do with their serverside JavaScript. Am trying to fix!

**Comment by CorvetteCole** [comment]
yo this issue should be fixed now. Also full material design is nearing completion
